#!/usr/bin/env node
/**
 * tokens.mjs — the ONE source of truth downstream of design-identity/tokens.json.
 *
 * Two jobs, both of which must be able to FAIL loudly:
 *   1. `--css`      emit design-identity/tokens.css from the JSON (never hand-edit the CSS).
 *   2. `--contrast` compute real WCAG 2.x relative-luminance contrast for every pair in
 *                   `contrastContract` and write design-identity/contrast.md.
 *
 * Exit code is 1 if any contracted pair misses its stated minimum. The numbers published in
 * IDENTITY.md are generated by this script, never typed by hand — a documented ratio that
 * nothing recomputes is a claim, not a measurement.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
export const PKG = join(HERE, "..");
export const TOKENS = JSON.parse(
  readFileSync(join(PKG, "design-identity", "tokens.json"), "utf8"),
);

/** #rrggbb -> [r,g,b] 0..255. Throws on anything else: silent NaN is how fake ratios happen. */
export function hexToRgb(hex) {
  const m = /^#([0-9a-f]{6})$/i.exec(String(hex).trim());
  if (!m) throw new Error(`not a 6-digit hex color: ${hex}`);
  const n = parseInt(m[1], 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

/** WCAG 2.x relative luminance. */
export function luminance(hex) {
  const [r, g, b] = hexToRgb(hex).map((v) => {
    const s = v / 255;
    return s <= 0.03928 ? s / 12.92 : ((s + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/** WCAG 2.x contrast ratio, 1..21. */
export function contrast(a, b) {
  const la = luminance(a);
  const lb = luminance(b);
  const [hi, lo] = la >= lb ? [la, lb] : [lb, la];
  return (hi + 0.05) / (lo + 0.05);
}

function emitCss() {
  const c = TOKENS.color;
  const t = TOKENS.type;
  const lines = [
    "/* GENERATED by tools/tokens.mjs --css from design-identity/tokens.json. Do not hand-edit. */",
    `/* Identity: ${TOKENS.$identity} — ${TOKENS.$status} */`,
    ":root {",
  ];
  for (const [k, v] of Object.entries(c)) lines.push(`  --color-${k}: ${v};`);
  lines.push(`  --font-sans: ${t.familySans};`);
  lines.push(`  --font-mono: ${t.familyMono};`);
  for (const [k, v] of Object.entries(t.scale)) {
    lines.push(`  --text-${k}: ${v.rem}rem;`);
    lines.push(`  --leading-${k}: ${v.lineHeight};`);
    lines.push(`  --tracking-${k}: ${v.tracking};`);
  }
  for (const [k, v] of Object.entries(t.weight)) lines.push(`  --weight-${k}: ${v};`);
  for (const [k, v] of Object.entries(TOKENS.space.scale))
    lines.push(`  --space-${String(k).replace(".", "_")}: ${v}px;`);
  for (const [k, v] of Object.entries(TOKENS.radius))
    lines.push(`  --radius-${k}: ${v}${k === "pill" ? "px" : "px"};`);
  for (const [k, v] of Object.entries(TOKENS.shadow)) lines.push(`  --shadow-${k}: ${v};`);
  for (const [k, v] of Object.entries(TOKENS.motion.durationMs))
    lines.push(`  --duration-${k}: ${v}ms;`);
  for (const [k, v] of Object.entries(TOKENS.motion.easing)) lines.push(`  --ease-${k}: ${v};`);
  lines.push(`  --target-min: ${TOKENS.target.minPx}px;`);
  lines.push(`  --target-recommended: ${TOKENS.target.recommendedPx}px;`);
  lines.push(`  --focus-ring-width: ${TOKENS.focus.ringWidthPx}px;`);
  lines.push(`  --focus-ring-offset: ${TOKENS.focus.ringOffsetPx}px;`);
  lines.push(`  --measure: ${TOKENS.type.measureCh.ideal}ch;`);
  lines.push("}");
  lines.push("");
  lines.push("/* Rule 8 of IDENTITY.md is a token, not a suggestion. */");
  lines.push("@media (prefers-reduced-motion: reduce) {");
  lines.push("  :root {");
  for (const k of Object.keys(TOKENS.motion.durationMs))
    lines.push(`    --duration-${k}: ${TOKENS.motion.reducedMotionDurationMs}ms;`);
  lines.push("  }");
  lines.push("}");
  const out = lines.join("\n") + "\n";
  writeFileSync(join(PKG, "design-identity", "tokens.css"), out);
  return out.length;
}

function emitContrast() {
  const c = TOKENS.color;
  const rows = [];
  let failures = 0;
  for (const entry of TOKENS.contrastContract) {
    const [fg, bg] = entry.pair;
    if (!(fg in c)) throw new Error(`contrastContract names unknown color ${fg}`);
    if (!(bg in c)) throw new Error(`contrastContract names unknown color ${bg}`);
    const ratio = contrast(c[fg], c[bg]);
    const pass = ratio >= entry.min;
    if (!pass) failures += 1;
    rows.push({ fg, bg, hexFg: c[fg], hexBg: c[bg], ratio, min: entry.min, pass, use: entry.use });
  }
  const md = [
    "# Contrast ledger — GENERATED",
    "",
    "Every number below is computed by `node tools/tokens.mjs --contrast` using the WCAG 2.x",
    "relative-luminance formula over `design-identity/tokens.json`. Nothing here is typed by hand.",
    "Regenerate after any color change; `scripts/smoke.sh` reruns it and fails the gate on a miss.",
    "",
    `Identity: **${TOKENS.$identity}** (${TOKENS.$status})`,
    `Generated by tools/tokens.mjs from tokens.json v${TOKENS.$version}.`,
    "",
    "```",
    "foreground        background        hex fg   hex bg    ratio   min   verdict  use",
  ];
  for (const r of rows) {
    md.push(
      [
        r.fg.padEnd(17),
        r.bg.padEnd(17),
        r.hexFg.padEnd(8),
        r.hexBg.padEnd(9),
        r.ratio.toFixed(2).padStart(5),
        String(r.min).padStart(5),
        (r.pass ? "PASS" : "FAIL").padStart(8),
        "  " + r.use,
      ].join(" "),
    );
  }
  md.push("```", "");
  md.push(
    failures === 0
      ? `All ${rows.length} contracted pairs meet their stated minimum.`
      : `**${failures} of ${rows.length} contracted pairs FAIL.** The identity is not shippable until fixed.`,
  );
  md.push("");
  writeFileSync(join(PKG, "design-identity", "contrast.md"), md.join("\n"));
  return { rows, failures };
}

if (process.argv[1] && process.argv[1].endsWith("tokens.mjs")) {
  const args = new Set(process.argv.slice(2));
  const all = args.size === 0 || args.has("--all");
  let failures = 0;
  if (all || args.has("--css")) console.log(`tokens.css written (${emitCss()} bytes)`);
  if (all || args.has("--contrast")) {
    const res = emitContrast();
    failures = res.failures;
    for (const r of res.rows)
      console.log(
        `${r.pass ? "PASS" : "FAIL"} ${r.fg} on ${r.bg}: ${r.ratio.toFixed(2)}:1 (min ${r.min})`,
      );
    console.log(`contrast.md written — ${res.rows.length} pairs, ${failures} failing`);
  }
  process.exit(failures === 0 ? 0 : 1);
}
